# Prophet model configuration

# Data configuration
target_column: "biastg"
frequency: "B"  # Business day frequency
fill_method: "ffill"
validation_split: 0.2

# Model parameters
seasonality_mode: "additive"
yearly_seasonality: true
weekly_seasonality: true
daily_seasonality: false
changepoint_prior_scale: 0.1
n_changepoints: 100
seasonality_prior_scale: 10.0
holidays_prior_scale: 10.0
country_holidays: "US"  # Set to null to disable

# Custom seasonalities
custom_seasonalities:
  - name: "quarterly"
    period: 91.25
    fourier_order: 10

# Forecasting parameters
forecast_horizon: 10
forecast_frequency: "D"  # D=daily, W=weekly, M=monthly, etc.

# Visualization
include_components: true

# Saving and output
save_model: true
save_results: true
model_dir: "outputs/models/prophet"
output_dir: "outputs/visualizations/prophet"
results_dir: "outputs/results/prophet"
