# Bias Correction Configuration

# Default output directory
output_dir: "outputs/generated_data/bias_corrected"

# Default correction method
method: "linear_scaling"

# Linear scaling settings
linear_correction_type: "both"  # Options: "additive", "scaling", "both"

# Quantile mapping settings
n_quantiles: 100

# Distribution mapping settings
distribution: "gamma"  # Options: "normal", "gamma"

# Delta change settings
delta_correction_type: "additive"  # Options: "additive", "multiplicative"

# Reference period for fitting (optional)
# reference_period:
#   - "2010-01-01"
#   - "2015-12-31"

# Regions for regional correction (optional)
regions:
  - name: "equatorial"
    lat_min: -10.0
    lat_max: 10.0
    lon_min: -180.0
    lon_max: 180.0
    
  - name: "north_atlantic"
    lat_min: 30.0
    lat_max: 60.0
    lon_min: -80.0
    lon_max: 0.0
    
  - name: "tropical_pacific"
    lat_min: -20.0
    lat_max: 20.0
    lon_min: 150.0
    lon_max: -120.0
