# NetCDF Processing Configuration

# Input/Output settings
output_dir: "outputs/generated_data/geolocations"
fill_missing: true
fill_method: "ffill"
resample_freq: "D"  # Daily frequency, set to null for no resampling

# Date ranges for processing data in separate folders
date_ranges:
  - name: "d10"
    start: "2010-01-01"
    end: "2010-12-31"
  - name: "d11"
    start: "2011-01-01"
    end: "2011-12-31"
  - name: "d12"
    start: "2012-01-01"
    end: "2012-12-31"
  - name: "d13"
    start: "2013-01-01"
    end: "2013-12-31"
  - name: "d14"
    start: "2014-01-01"
    end: "2014-12-31"
  - name: "d15"
    start: "2015-01-01"
    end: "2015-12-31"

# Variables to process if not specified at command line
variables:
  - "biastg"
  - "biastg"

# Regional filtering (if needed)
regions:
  - name: "equatorial"
    lat_min: -10.0
    lat_max: 10.0
    lon_min: -180.0
    lon_max: 180.0
  - name: "north_atlantic"
    lat_min: 30.0
    lat_max: 60.0
    lon_min: -80.0
    lon_max: 0.0

